version: "3.7"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecoil
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
        - ecoil-network

volumes:
    postgres-data:

networks:
    ecoil-network: